name: android master CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  apk:
    name: Generate Apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembleRelease
      - uses: actions/upload-artifact@v3.1.0
        with:
          name: upload-apk
          path: 
            ${{github.workspace}}/app/build/outputs/apk/release/*.apk
      - uses: toolmantim/release-drafter@v5.2.0
        name: Draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

     


      
