name: android master CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
   
    
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'


      - name: Release APK Publisher v2
        uses: vdesmond/action-release-apk@1.0.5
        with:
              GITHUB_TOKEN: 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

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - uses: actions/upload-artifact@v3.1.0
        with:
          name: upload-apk
          path: 
            ${{github.workspace}}/app/build/outputs/apk/release/*.apk
            
    
      
